import type { ReportMeta } from './types';

export const reportsConfig: ReportMeta[] = [
  {
    slug: 'annual-financial-statement',
    name: 'Annual Financial Statement',
    domain: 'Finance / Accounting',
    complexity: 'Complex',
    layout: 'Document',
    reportType: 'Financial',
    description:
      'Year-end financial statement for a mid-size company — income statement, balance sheet, and cash flow summary in a formal document layout with section dividers, accounting-style tables, and prior-year comparisons.',
    keyMetrics: ['Total Revenue', 'Net Income', 'Total Assets', 'Operating Cash Flow'],
    elements: ['Accounting tables', 'Variance columns', 'Branded header', 'Document footer', 'Bar chart', 'Section dividers'],
    status: 'available',
  },
  {
    slug: 'executive-business-review',
    name: 'Executive Business Review',
    domain: 'Corporate / C-Suite',
    complexity: 'Simple',
    layout: 'Wide',
    reportType: 'Executive',
    description:
      'CEO-level quarterly business review with large headline KPIs, a revenue trend chart, division performance summary table, and a written executive highlights section — designed for board presentation.',
    keyMetrics: ['Total Revenue', 'Gross Profit', 'EBITDA', 'Cash Position'],
    elements: ['Large KPI tiles', 'Bar chart', 'Summary table', 'Highlights text', 'Branded header', 'Board footer'],
    status: 'available',
  },
  {
    slug: 'patient-health-summary',
    name: 'Patient Health Summary',
    domain: 'Healthcare / Clinical',
    complexity: 'Medium',
    layout: 'Document',
    reportType: 'Clinical',
    description:
      'Clinical visit summary for a patient portal or physician handoff. Shows vital signs, active medications, recent lab results with reference ranges, and structured visit notes — no charts, entirely tables and text.',
    keyMetrics: ['Age', 'BMI', 'Blood Pressure', 'Last Visit Date'],
    elements: ['Patient info strip', 'Vital signs grid', 'Medications table', 'Lab results w/ status', 'Clinical notes', 'No charts'],
    status: 'available',
  },
  {
    slug: 'project-status-report',
    name: 'Project Status Report',
    domain: 'Project Management',
    complexity: 'Simple',
    layout: 'Mixed',
    reportType: 'Operational',
    description:
      'Weekly project health report with a RAG traffic-light banner, milestone timeline, budget vs. actual chart, and a risk register — giving a PM and stakeholders a single-page view of delivery status.',
    keyMetrics: ['% Complete', 'Days to Deadline', 'Budget Consumed', 'Open Risks'],
    elements: ['RAG status banner', 'Milestone timeline', 'Paired bar chart', 'Risk register table', 'Progress indicators'],
    status: 'available',
  },
  {
    slug: 'sales-pipeline-report',
    name: 'Sales Pipeline Report',
    domain: 'Sales / CRM',
    complexity: 'Medium',
    layout: 'Wide',
    reportType: 'Performance',
    description:
      'Monthly sales performance report with pipeline stage funnel, rep quota attainment rankings with inline progress bars, bookings vs. target chart, and deal size distribution.',
    keyMetrics: ['Pipeline Value', 'Deals Won', 'Avg. Deal Size', 'Win Rate'],
    elements: ['Funnel visualization', 'Rep ranking table', 'Inline progress bars', 'Composed chart', 'Bar chart'],
    status: 'coming-soon',
  },
  {
    slug: 'marketing-campaign-analysis',
    name: 'Marketing Campaign Analysis',
    domain: 'Marketing / Growth',
    complexity: 'Medium',
    layout: 'Wide',
    reportType: 'Performance',
    description:
      'Post-campaign report for a multi-channel digital marketing campaign — channel ROAS comparison, conversion funnel with drop-off annotations, audience breakdown donut, and campaign ROI summary table.',
    keyMetrics: ['Total Impressions', 'Conversions', 'Blended ROAS', 'Cost per Conversion'],
    elements: ['Grouped bar chart', 'Conversion funnel', 'Donut chart', 'ROI summary table', 'Drop-off annotations'],
    status: 'coming-soon',
  },
  {
    slug: 'supply-chain-ops-report',
    name: 'Supply Chain Operations Report',
    domain: 'Operations / Logistics',
    complexity: 'Complex',
    layout: 'Wide',
    reportType: 'Operational',
    description:
      'Monthly supply chain report with inventory level trends by category, supplier performance scorecard (color-coded by threshold), regional shipment breakdown, and a critical open orders table.',
    keyMetrics: ['On-time Delivery', 'Inventory Value', 'Stockout Events', 'Avg. Lead Time'],
    elements: ['Multi-series area chart', 'Supplier scorecard', 'Colored table cells', 'Horizontal bar chart', 'Critical orders table'],
    status: 'coming-soon',
  },
  {
    slug: 'employee-performance-review',
    name: 'Employee Performance Review',
    domain: 'Human Resources',
    complexity: 'Simple',
    layout: 'Document',
    reportType: 'Performance',
    description:
      'Annual employee review document with a prominent overall rating, competency radar chart, goal achievement table with status badges, peer feedback text blocks, a development plan, and a sign-off section.',
    keyMetrics: ['Overall Rating', 'Goals Achieved', '360° Score', 'Tenure'],
    elements: ['Radar chart', 'Rating display', 'Goal table', 'Feedback text blocks', 'Development plan', 'Sign-off area'],
    status: 'coming-soon',
  },
  {
    slug: 'security-incident-report',
    name: 'Cybersecurity Incident Report',
    domain: 'IT / Security',
    complexity: 'Medium',
    layout: 'Document',
    reportType: 'Compliance',
    description:
      'Formal post-incident report documenting a security event — TLP classification banner, severity badge, incident timeline, affected systems table, impact assessment, and remediation action tracker.',
    keyMetrics: ['Severity Level', 'Systems Affected', 'Records at Risk', 'Time to Containment'],
    elements: ['TLP classification', 'Severity badge', 'Vertical timeline', 'Affected systems table', 'Remediation tracker', 'Bar chart'],
    status: 'coming-soon',
  },
  {
    slug: 'esg-sustainability-report',
    name: 'ESG Sustainability Report',
    domain: 'Corporate / ESG',
    complexity: 'Complex',
    layout: 'Mixed',
    reportType: 'Compliance',
    description:
      'Annual ESG progress report with three color-themed sections (Environmental, Social, Governance), emissions trend, energy mix donut, diversity charts, board composition, ESG score gauge, and an industry benchmark radar.',
    keyMetrics: ['Carbon Emissions', 'Renewable Energy %', 'Workforce Diversity', 'Board Independence'],
    elements: ['3-section color themes', 'Progress bars to targets', 'Area chart', 'Donut chart', 'Radar chart', 'SDG alignment grid'],
    status: 'coming-soon',
  },
];
