/**
 * Generates docs/showcase-reference.md — the comprehensive design guide and AI training
 * document for the Ascendra UI showcase.
 *
 * Sources:
 *   lib/nav-config.ts        — showcase navigation structure
 *   lib/registry.ts          — primitive component metadata
 *   lib/forms-config.ts      — composite form patterns
 *   lib/dialogs-config.ts    — dialog patterns
 *   lib/sheets-config.ts     — sheet patterns
 *   lib/drawers-config.ts    — drawer patterns
 *   lib/dashboards-config.ts — dashboard patterns
 *   lib/reports-config.ts    — report patterns
 *
 * Run: npm run docs:generate
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { dashboardsConfig } from "../lib/dashboards-config";
import { dialogsConfig } from "../lib/dialogs-config";
import { drawersConfig } from "../lib/drawers-config";
import { formsConfig } from "../lib/forms-config";
import { navConfig } from "../lib/nav-config";
import { registry } from "../lib/registry";
import { reportsConfig } from "../lib/reports-config";
import { sheetsConfig } from "../lib/sheets-config";

const ascendraConfig = JSON.parse(
  readFileSync(join(process.cwd(), "ascendra.json"), "utf8")
) as { version: string; commit?: string };
const uiVersion = ascendraConfig.version;
const uiCommit = ascendraConfig.commit ?? "unknown";
const today = new Date().toISOString().slice(0, 10);

function esc(s: string) {
  return s.replace(/\|/g, "\\|");
}

// ── Count helpers ──────────────────────────────────────────────────────────────
const primitiveCount = Object.keys(registry).length;
const showcasePageCount = navConfig.reduce((sum, cat) => sum + cat.items.length, 0);

// ── Group primitive components by navConfig category ──────────────────────────
const categoryComponents = new Map<string, string[]>();
for (const cat of navConfig) {
  const names: string[] = [];
  for (const item of cat.items) {
    const bare = item.slug.split("/").pop()!;
    const meta = registry[item.slug] ?? registry[bare];
    if (meta) names.push(meta.name);
  }
  if (names.length) categoryComponents.set(cat.title, names);
}

// ── Identify all unique components across composite patterns ──────────────────
const formComponents = new Set(formsConfig.flatMap((f) => f.components));
const dialogComponents = new Set(dialogsConfig.flatMap((d) => d.components));
const sheetComponents = new Set(sheetsConfig.flatMap((s) => s.components));
const drawerComponents = new Set(drawersConfig.flatMap((d) => d.components));

// ── Chart type frequency analysis for dashboard guidance ──────────────────────
const chartFrequency = new Map<string, number>();
for (const d of dashboardsConfig) {
  for (const ct of d.chartTypes) {
    chartFrequency.set(ct, (chartFrequency.get(ct) ?? 0) + 1);
  }
}
const topCharts = [...chartFrequency.entries()]
  .sort((a, b) => b[1] - a[1])
  .slice(0, 6);

// ── Dashboard domain coverage ──────────────────────────────────────────────────
const dashboardDomains = dashboardsConfig.map((d) => d.domain).join(", ");

// ── Report domain coverage ────────────────────────────────────────────────────
const reportDomains = reportsConfig.map((r) => r.domain).join(", ");

// ── Form domain coverage ──────────────────────────────────────────────────────
const formDomains = [...new Set(formsConfig.map((f) => f.domain))].join(", ");

// ── Build document ─────────────────────────────────────────────────────────────

const lines: string[] = [
  `<!-- ascendra-ui-version: ${uiVersion} -->`,
  `<!-- ascendra-ui-commit: ${uiCommit} -->`,
  "# Ascendra UI — Showcase Reference",
  "",
  `> Auto-generated on ${today} · ascendra-ui v${uiVersion}`,
  "> Run `npm run docs:generate` after any config or showcase change.",
  "> For the component API reference (props, imports, types) see `docs/ui-reference.md`.",
  "",
  "---",
  "",
  "## Purpose of This Document",
  "",
  "This document is the **design guide and AI training reference** for Ascendra UI.",
  "It answers questions like:",
  "",
  "- _What visual patterns does this library use?_",
  "- _Which component should I reach for in a given situation?_",
  "- _How are pages and layouts composed?_",
  "- _What real-world scenarios does the showcase demonstrate?_",
  "- _How should I instruct an AI model to build a new feature using this library?_",
  "",
  "For the technical API (props, import paths, TypeScript types) see `docs/ui-reference.md`.",
  "",
  "---",
  "",
  "## Library at a Glance",
  "",
  `| Stat | Count |`,
  `|---|---|`,
  `| Primitive components | ${primitiveCount} |`,
  `| Composite form patterns | ${formsConfig.length} |`,
  `| Dialog patterns | ${dialogsConfig.length} |`,
  `| Sheet patterns | ${sheetsConfig.length} |`,
  `| Drawer patterns | ${drawersConfig.length} |`,
  `| Dashboard demos | ${dashboardsConfig.length} |`,
  `| Report demos | ${reportsConfig.length} |`,
  `| Showcase pages total | ${showcasePageCount} |`,
  "",
  "---",
  "",
  "## Design Philosophy",
  "",
  "Ascendra UI is a **premium admin panel component library** built for internal tools, SaaS products, and data-rich applications. It is not a general-purpose UI kit — it is optimized for complex multi-section pages, large forms, data tables, and analytical dashboards.",
  "",
  "### Core Principles",
  "",
  "**1. Depth over flatness**  ",
  "Components use a layered shadow and gloss system rather than flat borders. Buttons have a 4-layer shadow. Inputs show a shadow ring on pointer focus and a keyboard-only outline for accessibility. Cards and panels have subtle elevation.",
  "",
  "**2. Semantic color tokens, not raw palette values**  ",
  "Never use `text-red-500` directly. Instead use semantic tokens: `text-negative` (error), `text-positive` (success), `text-warning` (warning), `text-info` (informational), `text-muted-foreground` (de-emphasized). The library exposes `--brand`, `--positive`, `--negative`, `--warning`, `--info`, `--dimmed` as CSS custom properties that automatically adapt to dark mode.",
  "",
  "**3. Smart focus distinction**  ",
  "Pointer-device focus shows a shadow ring (visible but not intrusive). Keyboard focus shows a high-contrast outline ring. This is baked into Input, Button, Checkbox, etc. — do not override focus styles.",
  "",
  "**4. Layout through composition, not config**  ",
  "Page layout is assembled from discrete components (`PageLayout > Header + Nav + MainContainer > SideBar + ContentArea`) rather than a single mega-config prop. This makes each layer independently replaceable.",
  "",
  "**5. Forms always use the Field system**  ",
  "Never place a label adjacent to an input with ad-hoc spacing. Always use `Field > FieldLabel + Input` (or your control). This ensures consistent label alignment, error display (`FieldError`), and accessible `htmlFor` wiring.",
  "",
  "**6. Cards for settings, not content cards**  ",
  "The `Card` component is a settings-style card (header + collapsible panel + items), not a generic content card. Use it for forms, settings pages, and structured data. For generic content containers use `PageContent` / `MainContent`.",
  "",
  "**7. Dark mode first**  ",
  "Every token has a light and dark variant defined in `globals.css`. Dark mode is enabled via the `dark` class on `<html>` (managed by `ThemeProvider` from `next-themes`). Never hardcode light-only colors.",
  "",
  "---",
  "",
  "## Layout System",
  "",
  "### Application Shell",
  "",
  "The outer shell is assembled in `app/(app)/layout.tsx`. The hierarchy is:",
  "",
  "```",
  "PageLayout",
  "├── SideBarOverlay        ← mobile overlay backdrop",
  "├── Header                ← top navigation bar",
  "│   ├── HeaderLinks       ← breadcrumb / project name area",
  "│   │   └── HeaderLink    ← individual breadcrumb segment",
  "│   └── HeaderActions     ← right-side: ThemeToggle, NameAvatar, etc.",
  "├── Nav                   ← sticky secondary nav strip (tab-style links)",
  "│   └── NavLink           ← active-underline link",
  "└── MainContainer         ← flex row: sidebar + content",
  "    ├── SideBarToggle     ← hamburger button (mobile)",
  "    ├── SideBar",
  "    │   └── SideBarMain",
  "    │       └── SideBarMenu (basePath=\"/section\")",
  "    │           ├── SideBarMenuHeader (icon={LuIcon})",
  "    │           └── SideBarMenuContent",
  "    │               ├── SideBarMenuItem (path=\"/section/page\")",
  "    │               └── SideBarMenuItemGroup → SideBarMenuItem[]",
  "    └── ContentArea       ← main scrollable content column",
  "```",
  "",
  "### Page Content Structure",
  "",
  "Inside `ContentArea`, every page follows this wrapper hierarchy:",
  "",
  "```",
  "PageHeader                ← sticky top bar with title + action slot",
  "├── PageHeaderGroup       ← title/subtitle group",
  "│   ├── PageTitle",
  "│   └── PageSubtitle",
  "└── PageHeaderAction      ← right slot (buttons, badges)",
  "",
  "PageMain                  ← scrollable main region below header",
  "└── PageWrapper           ← horizontal padding + max-width",
  "    └── PageContent       ← vertical spacing between sections",
  "        └── MainContent   ← the content itself (grid, list, etc.)",
  "```",
  "",
  "Optional secondary navigation between `PageHeader` and `PageMain`:",
  "```",
  "Nav > NavLink[]           ← tab-style section switcher",
  "```",
  "",
  "### Layout Variants",
  "",
  "| Variant | When to use | Structure |",
  "|---|---|---|",
  "| **Single column** | Simple forms, settings | `MainContent > Card[]` |",
  "| **Two column** | Form + aside | `PageContent > grid cols-3` where main is `col-span-2` and `AsideContent` is `col-span-1` |",
  "| **Full width table** | Data-heavy pages | `MainContent` without `max-w` constraint, `TableWrapper` fills width |",
  "| **Dashboard grid** | Analytics | `MainContent > grid` with mixed `col-span` values for KPI tiles, charts, tables |",
  "",
  "### When to Use AsideContent",
  "",
  "`AsideContent` is a sidebar-within-a-page for supplementary info (related records, quick stats, help text). Use it when content logically divides into main + context panel. The `dimmed` prop overlays it when a form is in a loading/saving state.",
  "",
  "---",
  "",
  "## Component Selection Guide",
  "",
  "### Feedback & Status",
  "",
  "| Need | Component | Notes |",
  "|---|---|---|",
  "| Label a record status | `SimpleBadge` | semantic variants: default, green, red, amber, blue, violet, orange |",
  "| Label with gradient style | `BubbleBadge` | sizes sm/md/lg; use sparingly, higher visual weight |",
  "| Online / offline indicator | `StatusDot` | tiny halo dot; pairs with `SimpleBadge` in table cells |",
  "| Inline alert message | `SimpleAlert` | use inside forms for guidance; never use toast for form validation |",
  "| Transient notification | `toast()` + `<Toaster />` | mount Toaster in root layout; call `toast.success()`, `toast.error()` etc. |",
  "| Premium feature marker | `ProBadge` | blue-purple gradient; place next to feature names in settings |",
  "| Loading placeholder | `Skeleton` + presets | use `SkeletonTable`, `SkeletonStat`, `SkeletonCard` for structured loading states |",
  "| Progress indicator | `ProgressBar` | indeterminate for unknown duration; sized/colored variants |",
  "| Multi-step flow | `Stepper` | shows current step with completed/active/pending states |",
  "| Dirty form warning | `UnsavedChangesBar` | fixed-bottom bar; appears when `isDirty` is true |",
  "",
  "### Form Inputs",
  "",
  "| Need | Component | Notes |",
  "|---|---|---|",
  "| Text input | `Input` | always wrap in `Field` for label + errors |",
  "| Prefix / suffix / button addon | `InputGroup` | e.g. URL prefix, currency suffix, search button |",
  "| Short list select | `Select` | ≤ 20 options; use `SelectTrigger` + `SelectContent` + `SelectItem` |",
  "| Searchable select, multi-select | `Combobox` | built-in search; multi mode shows chips |",
  "| Large dataset lookup | `TableLookup` | tabular popup with async search; single or multi mode |",
  "| Toggle boolean | `Switch` | for settings and preferences |",
  "| Agree / multi-select | `Checkbox` | individual item; use `FieldSet > FieldGroup` for a group |",
  "| Single pick from small set | `RadioGroup` + `RadioGroupItem` | ≤ 6 options; wrap in `FieldSet` |",
  "| Date | `DatePicker` | single date selection |",
  "| Date range | `DateRangePicker` | shows 2-month calendar |",
  "| Rich content | `RichTextEditor` | Tiptap-based; bold, italic, lists, links |",
  "| File | `FileUpload` | dropzone / button / inline variants; managed upload states |",
  "| Color | `ColorPicker` | HSL sliders + hex input + presets grid |",
  "",
  "### Always use Field wrappers",
  "",
  "```tsx",
  "// Correct",
  "<Field orientation=\"horizontal\">",
  "  <FieldLabel htmlFor=\"email\">Email</FieldLabel>",
  "  <FieldContent>",
  "    <Input id=\"email\" {...register('email')} />",
  "    <FieldError errors={errors.email ? [errors.email] : []} />",
  "  </FieldContent>",
  "</Field>",
  "",
  "// Wrong — raw label + input",
  "<label>Email</label>",
  "<input ... />",
  "```",
  "",
  "### Navigation",
  "",
  "| Need | Component | Notes |",
  "|---|---|---|",
  "| External / internal text link | `Anchor` | variants: primary (brand color), blue, muted |",
  "| Tab-style page links | `NavLink` | active underline driven by pathname |",
  "| Horizontal link strip | `Nav > NavLink[]` | sticky strip; used for sub-section navigation |",
  "| Breadcrumb header | `Header > HeaderLinks > HeaderLink` | use slash separators via `HeaderSlash` |",
  "| App sidebar nav | `SideBarMenu` system | see layout guide above |",
  "| Global search / commands | `CommandPalette` + `useCommandPalette` | ⌘K registered automatically |",
  "",
  "### Overlays",
  "",
  "| Need | Component | Notes |",
  "|---|---|---|",
  "| Confirm an action | `Dialog` | centered modal; use for short confirmations and form inputs |",
  "| Destroy / irreversible action | `Dialog` with `variant=\"destructive\"` on the confirm button | |",
  "| Detail / preview panel | `Sheet` side=\"right\" | slides in from right; use for record detail, preview |",
  "| Settings panel | `Sheet` side=\"right\" | wider than dialog; use when form has many fields |",
  "| Mobile action menu | `Drawer` | slides up from bottom; use for mobile-first action flows |",
  "| Contextual menu | `DropdownMenu` | right-click or button trigger; supports sub-menus, checkboxes |",
  "| Hover help | `Tooltip` | short label only; for longer help use `FieldDescription` |",
  "",
  "**Rule:** Use Dialog for ≤ 4 fields and destructive confirmations. Use Sheet for ≥ 5 fields or complex forms. Use Drawer for mobile-first interactions.",
  "",
  "### Data Display",
  "",
  "| Need | Component | Notes |",
  "|---|---|---|",
  "| Simple data list | `Table` system | no search/sort/filter; use inside dashboards |",
  "| Full-featured data grid | `DataTable` system | search, filter, sort, column manager, pagination |",
  "| Empty list state | `Empty` | with `EmptyMedia` icon variant and `EmptyContent` CTA |",
  "| Clickable list items | `Item` system | media + title + description + actions slots |",
  "| KPI tile | `Card` with `CardPanel > CardPanelItem` | use in dashboard grids |",
  "| Analytics charts | Recharts via `CardPanel` | Line, Area, Bar, Pie, Radial, etc. |",
  "| Interactive stars | `Rating` | `onChange` makes it interactive; omit for read-only |",
  "",
  "### Utilities",
  "",
  "| Need | Component | Notes |",
  "|---|---|---|",
  "| Copy to clipboard | `CopyText` | wrap any element; `showTooltip` for confirmation |",
  "| User avatar | `NameAvatar` | deterministic color from name; optional `href` |",
  "| Theme switcher | `ThemeToggle` | places in `HeaderActions` |",
  "| Page navigation | `PaginationButton` | prev/next bordered buttons |",
  "| Table row action | `RowActionButton` | hidden by default; visible on row hover |",
  "| Route scroll reset | `ScrollToTop` | place once in root layout; no props needed |",
  "| Collapsible calendar | `Calendar` | single, multiple, or range mode |",
  "| Tabbed layout | `Tabs > TabList > TabTrigger` | `dirty` prop shows unsaved-changes dot |",
  "",
  "---",
  "",
  "## Primitive Components by Category",
  "",
  ...navConfig
    .filter((cat) => categoryComponents.has(cat.title))
    .map((cat) => {
      const names = categoryComponents.get(cat.title)!;
      return [
        `### ${cat.title}`,
        "",
        `**Components:** ${names.join(" · ")}`,
        "",
        "**Showcase pages:**",
        "",
        ...cat.items.map((item) => {
          const bare = item.slug.split("/").pop()!;
          const meta = registry[item.slug] ?? registry[bare];
          if (!meta) return "";
          return `- [\`/showcase/${item.slug}\`](/showcase/${item.slug}) — **${item.name}**: ${meta.description}`;
        }).filter(Boolean),
        "",
      ].join("\n");
    }),
  "",
  "---",
  "",
  "## Composite Patterns",
  "",
  "> Composite patterns are full-page or full-panel implementations that combine multiple",
  "> primitives into a realistic domain scenario. Study these to understand how components",
  "> are assembled together in production-quality code.",
  "",
  "### Forms",
  "",
  `${formsConfig.length} form patterns covering: ${formDomains}.`,
  "",
  "#### Form Component Palette",
  "",
  `The following primitives appear across all form patterns: ${[...formComponents].join(", ")}.`,
  "",
  "#### Form Complexity Guide",
  "",
  "| Complexity | Characteristics | Examples |",
  "|---|---|---|",
  `| Simple | Single section, vertical layout, ≤ 6 fields | ${formsConfig.filter((f) => f.complexity === "Simple").map((f) => f.name).join(", ")} |`,
  `| Medium | 2–3 sections or conditional logic, 7–15 fields | ${formsConfig.filter((f) => f.complexity === "Medium").map((f) => f.name).join(", ")} |`,
  `| Complex | Multi-section, multi-step, ≥ 15 fields, file uploads, rich text | ${formsConfig.filter((f) => f.complexity === "Complex").map((f) => f.name).join(", ")} |`,
  "",
  "#### All Form Patterns",
  "",
  "| Name | Route | Domain | Complexity | Layout | Edit Mode |",
  "|---|---|---|---|---|---|",
  ...formsConfig.map(
    (f) =>
      `| **${esc(f.name)}** | [\`/showcase/forms/${f.slug}\`](/showcase/forms/${f.slug}) | ${f.domain} | ${f.complexity} | ${esc(f.layout)} | ${f.hasEditMode ? "Yes" : "No"} |`
  ),
  "",
  "#### Form Pattern Details",
  "",
  ...formsConfig.map((f) =>
    [
      `##### ${f.name}`,
      "",
      `_Route:_ \`/showcase/forms/${f.slug}\`  `,
      `_Domain:_ ${f.domain} · _Complexity:_ ${f.complexity}  `,
      `_Layout:_ ${f.layout}${f.hasEditMode ? "  \n_Edit mode:_ Ships with a read-only view and an Edit toggle" : ""}`,
      "",
      f.description,
      "",
      `_Components used:_ ${f.components.join(", ")}`,
      "",
    ].join("\n")
  ),
  "---",
  "",
  "### Dialogs",
  "",
  `${dialogsConfig.length} dialog patterns. All rendered on a single gallery page at \`/showcase/dialogs\`.`,
  "",
  "#### When to Use Dialog vs Sheet vs Drawer",
  "",
  "- **Dialog** — short confirmations (≤ 4 fields), destructive actions, feature announcements",
  "- **Sheet** — side panels for record detail, longer forms (≥ 5 fields), settings",
  "- **Drawer** — bottom-up panels for mobile-first flows, action menus, quick inputs",
  "",
  "#### Dialog Type Definitions",
  "",
  "| Type | Intent | Typical buttons |",
  "|---|---|---|",
  "| Confirmation | Ask user to confirm a safe action | Cancel + Confirm |",
  "| Destructive | Confirm an irreversible action | Cancel + Delete/Remove (red) |",
  "| Input | Collect a small amount of data | Cancel + Save |",
  "| Alert | Display important information | OK / Dismiss |",
  "| Feature | Announce or explain a feature | Close or CTA |",
  "",
  "#### All Dialog Patterns",
  "",
  "| Name | Type | Components |",
  "|---|---|---|",
  ...dialogsConfig.map(
    (d) =>
      `| **${esc(d.name)}** | ${d.type} | ${d.components.join(", ")} |`
  ),
  "",
  "---",
  "",
  "### Sheets",
  "",
  `${sheetsConfig.length} slide-out panel patterns for detail, preview, activity, and settings flows.`,
  "All rendered on a single gallery page at `/showcase/sheets`.",
  "",
  "#### Sheet Type Definitions",
  "",
  "| Type | Intent | Typical content |",
  "|---|---|---|",
  "| Detail | Full record detail view | Read-only fields, sections, related items |",
  "| Preview | Quick-look without leaving context | Compact summary, key metrics |",
  "| Activity | Timeline or audit log | Chronological events list |",
  "| Settings | Configuration panel | Form fields, switches, selects |",
  "",
  "#### All Sheet Patterns",
  "",
  "| Name | Type | Domain | Components |",
  "|---|---|---|---|",
  ...sheetsConfig.map(
    (s) =>
      `| **${esc(s.name)}** | ${s.type} | ${s.domain} | ${s.components.join(", ")} |`
  ),
  "",
  "---",
  "",
  "### Drawers",
  "",
  `${drawersConfig.length} bottom-drawer patterns for mobile-first flows.`,
  "All rendered on a single gallery page at `/showcase/drawers`.",
  "",
  "#### Drawer Type Definitions",
  "",
  "| Type | Intent |",
  "|---|---|",
  "| Action | Quick action menu; list of actionable options |",
  "| Panel | Richer content panel that slides up from bottom |",
  "| Preview | Compact record preview for mobile |",
  "| Input | Short form or data entry on mobile |",
  "",
  "#### All Drawer Patterns",
  "",
  "| Name | Type | Domain | Components |",
  "|---|---|---|---|",
  ...drawersConfig.map(
    (d) =>
      `| **${esc(d.name)}** | ${d.type} | ${d.domain} | ${d.components.join(", ")} |`
  ),
  "",
  "---",
  "",
  "### Dashboards",
  "",
  `${dashboardsConfig.length} full analytics dashboard pages. Each has KPI tiles, multiple chart types, and a data table.`,
  `Domains covered: ${dashboardDomains}.`,
  "",
  "#### Chart Type Frequency",
  "",
  "The most commonly used chart types across all dashboards:",
  "",
  ...topCharts.map(([type, count]) => `- **${type}** — used in ${count} dashboard${count > 1 ? "s" : ""}`),
  "",
  "#### Dashboard Layout Pattern",
  "",
  "Every dashboard page follows a consistent structure:",
  "",
  "```",
  "PageHeader (title + date range badge)",
  "PageMain > PageWrapper > PageContent",
  "  Row 1: KPI tiles (grid of 4 — col-span-3 each on 12-col grid)",
  "  Row 2+: Charts + Tables (mixed col-span via 12-column grid)",
  "  Final row: Full-width Table (col-span-12)",
  "```",
  "",
  "KPI tiles always use `Card > CardPanel > CardPanelItem` with a metric value, label, and change indicator.",
  "",
  "#### All Dashboard Patterns",
  "",
  "| Name | Route | Domain | KPIs | Chart types |",
  "|---|---|---|---|---|",
  ...dashboardsConfig.map(
    (d) =>
      `| **${esc(d.name)}** | [\`/showcase/dashboards/${d.slug}\`](/showcase/dashboards/${d.slug}) | ${d.domain} | ${d.kpis.join(", ")} | ${d.chartTypes.join(", ")} |`
  ),
  "",
  "---",
  "",
  "### Reports",
  "",
  `${reportsConfig.length} document-style report pages.`,
  `Domains covered: ${reportDomains}.`,
  "",
  "#### Report vs Dashboard",
  "",
  "| Dimension | Dashboard | Report |",
  "|---|---|---|",
  "| Purpose | Live operational monitoring | Periodic review, export-ready summary |",
  "| Layout | Wide grid, dense data | Document-style, print-friendly |",
  "| Charts | Multiple interactive charts | Supporting charts only |",
  "| Tables | Scrollable DataTable | Simple Table with summary rows |",
  "| Audience | Operations team | Executives, auditors, HR |",
  "",
  "#### Report Type Definitions",
  "",
  "| Type | Focus |",
  "|---|---|",
  "| Executive | High-level KPIs for leadership |",
  "| Financial | Revenue, P&L, cost analysis |",
  "| Operational | Process efficiency, throughput |",
  "| Performance | Individual or team metrics |",
  "| Clinical | Healthcare outcomes, patient data |",
  "| Compliance | Audit trails, regulatory adherence |",
  "",
  "#### All Report Patterns",
  "",
  "| Name | Route | Domain | Type | Complexity |",
  "|---|---|---|---|---|",
  ...reportsConfig.map(
    (r) =>
      `| **${esc(r.name)}** | [\`/showcase/reports/${r.slug}\`](/showcase/reports/${r.slug}) | ${r.domain} | ${r.reportType} | ${r.complexity} |`
  ),
  "",
  "---",
  "",
  "## Showcase Navigation Map",
  "",
  `The showcase has ${showcasePageCount} pages organized into ${navConfig.length} categories.`,
  "All routes are prefixed with \`/showcase\`.",
  "",
  "| Category | Pages |",
  "|---|---|",
  ...navConfig.map(
    (cat) =>
      `| **${cat.title}** | ${cat.items.map((i) => `[\`${i.slug || "/"}\`](/showcase/${i.slug})`).join(", ")} |`
  ),
  "",
  "---",
  "",
  "## AI Developer Guide",
  "",
  "> Use this section to write effective prompts for AI models working with this codebase.",
  "",
  "### How to Ask an AI to Build a New Page",
  "",
  "Include the following context in your prompt:",
  "",
  "```",
  "I am working in a Next.js project that uses Ascendra UI.",
  "All components are imported from @/ascendra-ui (or @/ascendra-ui/shadcn for Tooltip).",
  "See docs/ui-reference.md for full props and docs/showcase-reference.md for patterns.",
  "",
  "Build [describe the page]. Requirements:",
  "- Use the standard page shell: PageHeader + PageMain + PageWrapper + PageContent + MainContent",
  "- Wrap all inputs in Field with FieldLabel and FieldError",
  "- Use Card + CardPanel + CardPanelItem for settings sections",
  "- Use SimpleBadge for status labels (not custom spans)",
  "- Use UnsavedChangesBar for forms (isDirty, onSave, onReset)",
  "- Follow the layout guide in docs/showcase-reference.md",
  "```",
  "",
  "### Common Mistakes to Avoid",
  "",
  "| Wrong | Correct |",
  "|---|---|",
  "| Raw `<label>` + `<input>` | `Field > FieldLabel + Input` |",
  "| `bg-red-500` for error color | `text-negative` / `bg-destructive` |",
  "| Custom div for card | `Card > CardPanel > CardPanelItem` |",
  "| `alert()` for confirmations | `Dialog` with Cancel + Confirm |",
  "| Large form in Dialog | Move to `Sheet` (side panel) |",
  "| Mobile menu in Dialog | Use `Drawer` (bottom sheet) |",
  "| DataTable inside dashboard | Use `Table` system (simpler, no built-in state) |",
  "| Inline toast for form errors | Use `FieldError` + `SimpleAlert` inside the form |",
  "| Hardcoded dark mode colors | Use semantic tokens (`--foreground`, `--muted-foreground`) |",
  "",
  "### Page Templates by Domain",
  "",
  "**Settings page** → Study `User Profile Settings` form at `/showcase/forms/user-profile`  ",
  "**Data list with actions** → Study `DataTable` at `/showcase/data-table`  ",
  "**Confirmation flow** → Study Dialog patterns at `/showcase/dialogs`  ",
  "**Analytics overview** → Study any dashboard at `/showcase/dashboards/saas-revenue`  ",
  "**Document report** → Study report pages at `/showcase/reports/`  ",
  "**Mobile-first flow** → Study Drawer patterns at `/showcase/drawers`  ",
  "",
  "### Component Naming Conventions",
  "",
  "- Components named `Page*` belong to the page shell (`PageHeader`, `PageMain`, `PageWrapper`, `PageContent`, `PageTitle`, `PageSubtitle`)",
  "- Components named `SideBar*` belong to the sidebar system",
  "- Components named `Card*` belong to the settings card system — not generic cards",
  "- Components named `Field*` belong to the form field wrapper system",
  "- Components named `DataTable*` belong to the advanced table with built-in state",
  "- Components named `Table*` belong to the simple table without built-in state",
  "- Compound component families share a prefix: `Sheet`, `SheetContent`, `SheetHeader`, `SheetTitle`, etc.",
  "",
  "### Import Paths",
  "",
  "```tsx",
  "// All ascendra-ui components",
  "import { Button, Input, Field, Card, ... } from '@/ascendra-ui'",
  "",
  "// Tooltip only (from shadcn layer)",
  "import { Tooltip, TooltipContent, TooltipTrigger } from '@/ascendra-ui/shadcn'",
  "```",
  "",
  "Never import from sub-paths like `@/ascendra-ui/components/button` — always use the barrel exports.",
  "",
  "---",
  "",
  "## Versioning",
  "",
  `This reference was generated for **ascendra-ui v${uiVersion}**.`,
  `Commit: \`${uiCommit}\``,
  "",
  "Run `npm run docs:generate` to regenerate after any change.",
  "Run `npm run release` to cut a new version.",
  "",
];

const outPath = join(process.cwd(), "docs", "showcase-reference.md");
writeFileSync(outPath, lines.join("\n"), "utf8");

console.log(
  `✓ Generated docs/showcase-reference.md · ascendra-ui v${uiVersion} (${showcasePageCount} showcase pages, ${formsConfig.length} forms, ${dashboardsConfig.length} dashboards, ${reportsConfig.length} reports)`
);
